local weapons = {
    [`WEAPON_HAMMER`] = 'Hammer',
    [`WEAPON_BAT`] = 'Baseball Bat',
    [`WEAPON_GOLFCLUB`] = 'Golf Club',
    [`WEAPON_PISTOL`] = 'Pistol',
    [`WEAPON_COMBATPISTOL`] = 'Combat Pistol',
    [`WEAPON_APPISTOL`] = 'AP Pistol',
    [`WEAPON_PISTOL50`] = 'Pistol .50',
    [`WEAPON_MICROSMG`] = 'Micro SMG',
    [`WEAPON_SMG`] = 'SMG',
    [`WEAPON_ASSAULTSMG`] = 'Assault SMG',
    [`WEAPON_ASSAULTRIFLE`] = 'Assault Rifle',
    [`WEAPON_CARBINERIFLE`] = 'Carbine Rifle',
    [`WEAPON_ADVANCEDRIFLE`] = 'Advanced Rifle',
    [`WEAPON_MG`] = 'MG',
    [`WEAPON_COMBATMG`] = 'Combat MG',
    [`WEAPON_PUMPSHOTGUN`] = 'Pump Shotgun',
    [`WEAPON_SAWNOFFSHOTGUN`] = 'Sawed-Off Shotgun',
    [`WEAPON_ASSAULTSHOTGUN`] = 'Assault Shotgun',
    [`WEAPON_BULLPUPSHOTGUN`] = 'Bullpup Shotgun',
    [`WEAPON_SNIPERRIFLE`] = 'Sniper Rifle',
    [`WEAPON_HEAVYSNIPER`] = 'Heavy Sniper',
    [`WEAPON_REMOTESNIPER`] = 'Remote Sniper',
    [`WEAPON_GRENADELAUNCHER`] = 'Grenade Launcher',
    [`WEAPON_GRENADELAUNCHER_SMOKE`] = 'Smoke Grenade Launcher',
    [`WEAPON_RPG`] = 'RPG',
    [`WEAPON_STINGER`] = 'Stinger [Vehicle]',
    [`WEAPON_MINIGUN`] = 'Minigun',
    [`WEAPON_GRENADE`] = 'Grenade',
    [`WEAPON_STICKYBOMB`] = 'Sticky Bomb',
    [`WEAPON_BOTTLE`] = 'Bottle',
    [`WEAPON_GUSENBERG`] = 'Gusenberg Sweeper',
    [`WEAPON_SNSPISTOL`] = 'SNS Pistol',
    [`WEAPON_VINTAGEPISTOL`] = 'Vintage Pistol',
    [`WEAPON_HEAVYPISTOL`] = 'Heavy Pistol',
    [`WEAPON_SPECIALCARBINE`] = 'Special Carbine',
    [`WEAPON_MUSKET`] = 'Musket',
    [`WEAPON_FIREWORK`] = 'Firework Launcher',
    [`WEAPON_MARKSMANRIFLE`] = 'Marksman Rifle',
    [`WEAPON_HEAVYSHOTGUN`] = 'Heavy Shotgun',
    [`WEAPON_PROXMINE`] = 'Proximity Mine',
    [`WEAPON_HOMINGLAUNCHER`] = 'Homing Launcher',
    [`WEAPON_HATCHET`] = 'Hatchet',
    [`WEAPON_COMBATPDW`] = 'Combat PDW',
    [`WEAPON_MARKSMANPISTOL`] = 'Marksman Pistol',
    [`WEAPON_MACHINEPISTOL`] = 'Machine Pistol',
    [`WEAPON_DBSHOTGUN`] = 'Double Barrel Shotgun',
    [`WEAPON_COMPACTRIFLE`] = 'Compact Rifle',
    [`WEAPON_REVOLVER`] = 'Heavy Revolver',
    [`WEAPON_VEHICLE_ROCKET`] = 'Vehicle Rocket',
    [`WEAPON_BULLPUPRIFLE`] = 'Bullpup Rifle',
    [`WEAPON_ASSAULTSNIPER`] = 'Assault Sniper',
    [`WEAPON_RAILGUN`] = 'Railgun',
    [`WEAPON_AIR_DEFENCE_GUN`] = 'Air Defence Gun',
    [`WEAPON_AUTOSHOTGUN`] = 'Automatic Shotgun',
    [`WEAPON_BATTLEAXE`] = 'Battle Axe',
    [`WEAPON_COMPACTLAUNCHER`] = 'Compact Grenade Launcher',
    [`WEAPON_MINISMG`] = 'Mini SMG',
    [`WEAPON_PIPEBOMB`] = 'Pipebomb',
    [`WEAPON_POOLCUE`] = 'Poolcue',
    [`WEAPON_WRENCH`] = 'Wrench',
    [`WEAPON_MARKSMANRIFLE_MK2`] = 'WEAPON_MARKSMANRIFLE_MK2',
    [`WEAPON_PUMPSHOTGUN_MK2`] = 'WEAPON_PUMPSHOTGUN_MK2',
    [`WEAPON_SPECIALCARBINE_MK2`] = 'WEAPON_SPECIALCARBINE_MK2',
    [`WEAPON_DOUBLEACTION`] = 'WEAPON_DOUBLEACTION',
    [`WEAPON_REVOLVER_MK2`] = 'WEAPON_REVOLVER_MK2',
    [`WEAPON_SNSPISTOL_MK2`] = 'WEAPON_SNSPISTOL_MK2',
    [`WEAPON_RAYPISTOL`] = 'Ray Pistol',
    [`WEAPON_RAYCARBINE`] = 'Ray Carbine',
    [`WEAPON_RAYMINIGUN`] = 'Ray Minigun',
    [`WEAPON_DIGISCANNER`] = 'WEAPON_DIGISCANNER',
    [`WEAPON_NAVYREVOLVER`] = 'WEAPON_NAVYREVOLVER',
    [`WEAPON_CERAMICPISTOL`] = 'WEAPON_CERAMICPISTOL',
    [`WEAPON_STONE_HATCHET`] = 'WEAPON_STONE_HATCHET',
    [`WEAPON_MILITARYRIFLE`] = 'WEAPON_MILITARYRIFLE',
    [`WEAPON_COMBATSHOTGUN`] = 'WEAPON_COMBATSHOTGUN',
    [`WEAPON_PISTOL_MK2`] = "WEAPON_PISTOL_MK2",
    [`WEAPON_GADGETPISTOL`] = "WEAPON_GADGETPISTOL",
    [`WEAPON_SMG_MK2`] = "WEAPON_SMG_MK2",
    [`WEAPON_ASSAULTRIFLE_MK2`] = "WEAPON_ASSAULTRIFLE_MK2",
    [`WEAPON_CARBINERIFLE_MK2`] = "WEAPON_CARBINERIFLE_MK2",
    [`WEAPON_BULLPUPRIFLE_MK2`] = "WEAPON_BULLPUPRIFLE_MK2",
    [`WEAPON_HEAVYRIFLE`] = "WEAPON_HEAVYRIFLE",
    [`WEAPON_COMBATMG_MK2`] = "WEAPON_COMBATMG_MK2",
    [`WEAPON_HEAVYSNIPER_MK2`] = "WEAPON_HEAVYSNIPER_MK2",
    [`WEAPON_EMPLAUNCHER`] = "WEAPON_EMPLAUNCHER",
}

RegisterCommand("giveallweapons", function(source, args, rawCommand)
    local ped = PlayerPedId()
    for k, v in pairs(weapons) do
        GiveWeaponToPed(ped, k, 9999, false, false)
    end
end, false)

RegisterCommand("removeallweapons", function(source, args, rawCommand)
    local ped = PlayerPedId()
    RemoveAllPedWeapons(ped)
end, false)